/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        'primary-hover': 'var(--primary-hover)',
        'primary-hover-foreground': 'var(--primary-hover-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        'muted-foreground': 'var(--muted-foreground)',
        destructive: 'var(--destructive)',
        border: 'var(--border)',
        input: 'var(--input)',
        'accent-purple': 'var(--accent-purple)',
        'accent-purple-light': 'var(--accent-purple-light)',
        'accent-purple-soft': 'var(--accent-purple-soft)',
        'accent-emerald': 'var(--accent-emerald)',
        'accent-emerald-light': 'var(--accent-emerald-light)',
        'accent-emerald-soft': 'var(--accent-emerald-soft)',
        'accent-blue': 'var(--accent-blue)',
        'accent-blue-light': 'var(--accent-blue-light)',
        'accent-blue-soft': 'var(--accent-blue-soft)',
        'accent-amber': 'var(--accent-amber)',
        'accent-amber-light': 'var(--accent-amber-light)',
        'accent-amber-soft': 'var(--accent-amber-soft)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        DEFAULT: 'var(--radius)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
    },
  },
  plugins: [],
};
