openapi: 3.0.0
info:
  title: test
  version: 1.0.0
paths:
  /api/authentication/login:
    post:
      summary: Login User
      operationId: Login User
      description: ''
      tags:
        - >-
          /Users/maxuden/Studium/BHT/jurilib/.bruno/Authentication/Login
          User.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: Content-Type
          in: header
          description: ''
          required: true
          example: application/json
      requestBody:
        $ref: '#/components/requestBodies/login_user'
  /api/appointment/employee/:employeeID:
    post:
      summary: Create Appointment
      operationId: Create Appointment
      description: ''
      tags:
        - >-
          /Users/maxuden/Studium/BHT/jurilib/.bruno/Appointments/single
          Appointment/Create Appointment.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: employeeID
          in: query
          description: ''
          required: true
          example: '{{employeeID}}'
      requestBody:
        $ref: '#/components/requestBodies/create_appointment'
  /api/appointment/employee/:employeeID/:appointmentID:
    get:
      summary: Get Appointment
      operationId: Get Appointment
      description: ''
      tags:
        - >-
          /Users/maxuden/Studium/BHT/jurilib/.bruno/Appointments/single
          Appointment/Get Appointment.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: appointmentID
          in: query
          description: ''
          required: true
          example: '{{appointmentID}}'
        - name: employeeID
          in: query
          description: ''
          required: true
          example: '{{employeeID}}'
  /api/appointment/employee/b1b66812-81a0-44a7-8ed5-84a7948a03f9/776af1b3-cd6e-4876-91e9-efdc472f0c87/confirm:
    post:
      summary: Confirm Appointment
      operationId: Confirm Appointment
      description: ''
      tags:
        - >-
          /Users/maxuden/Studium/BHT/jurilib/.bruno/Appointments/single
          Appointment/Confirm appointment/Confirm Appointment.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: Content-Type
          in: header
          description: ''
          required: true
          example: application/json
  /api/appointment/:appointmentID/request:
    post:
      summary: request appointment
      operationId: request appointment
      description: ''
      tags:
        - >-
          /Users/maxuden/Studium/BHT/jurilib/.bruno/Appointments/user booking
          workflow/book appointment.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: appointmentID
          in: query
          description: ''
          required: true
          example: '{{appointmentID}}'
        - name: ''
          in: header
          description: ''
          required: true
          example: ''
  /api/appointment/:appointmentID/cancel:
    post:
      summary: cancel appointment
      operationId: cancel appointment
      description: ''
      tags:
        - >-
          /Users/maxuden/Studium/BHT/jurilib/.bruno/Appointments/user booking
          workflow/cancel appointment.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: appointmentID
          in: query
          description: ''
          required: true
          example: '{{appointmentID}}'
        - name: ''
          in: header
          description: ''
          required: true
          example: ''
  /api/case/:
    post:
      summary: Create Case
      operationId: Create Case
      description: ''
      tags:
        - /Users/maxuden/Studium/BHT/jurilib/.bruno/Case/Create Case.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: Content-Type
          in: header
          description: ''
          required: true
          example: application/json
      requestBody:
        $ref: '#/components/requestBodies/create_case'
  /api/case/:caseID:
    delete:
      summary: Delete Case
      operationId: Delete Case
      description: ''
      tags:
        - /Users/maxuden/Studium/BHT/jurilib/.bruno/Case/Delete Case.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: caseID
          in: query
          description: ''
          required: true
          example: '{{caseID}}'
    patch:
      summary: Update Case
      operationId: Update Case
      description: ''
      tags:
        - /Users/maxuden/Studium/BHT/jurilib/.bruno/Case/Update Case.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: caseID
          in: query
          description: ''
          required: true
          example: '{{caseID}}'
      requestBody:
        $ref: '#/components/requestBodies/update_case'
  /api/case/user/:userID:
    get:
      summary: Get Cases
      operationId: Get Cases
      description: ''
      tags:
        - /Users/maxuden/Studium/BHT/jurilib/.bruno/Case/User/Get Cases.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: userID
          in: query
          description: ''
          required: true
          example: '{{userID}}'
  /api/case/employee/:employeeID:
    get:
      summary: Get Cases
      operationId: Get Cases
      description: ''
      tags:
        - /Users/maxuden/Studium/BHT/jurilib/.bruno/Case/Employee/Get Cases.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: employeeID
          in: query
          description: ''
          required: true
          example: '{{employeeID}}'
  /api/organization:
    get:
      summary: All Organizations
      operationId: All Organizations
      description: ''
      tags:
        - >-
          /Users/maxuden/Studium/BHT/jurilib/.bruno/Organization/All
          Organizations.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: priceCategory
          in: query
          description: ''
          required: false
          example: ''
        - name: organizationType
          in: query
          description: ''
          required: false
          example: ''
        - name: area
          in: query
          description: ''
          required: false
          example: ''
        - name: city
          in: query
          description: ''
          required: false
          example: ''
        - name: languages
          in: query
          description: ''
          required: false
          example: ''
        - name: accessibility
          in: query
          description: ''
          required: false
          example: ''
  /api/organization/:organizationID/services:
    get:
      summary: All Services
      operationId: All Services
      description: ''
      tags:
        - /Users/maxuden/Studium/BHT/jurilib/.bruno/Services/All Services.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: organizationID
          in: query
          description: ''
          required: true
          example: '{{organizationID}}'
    post:
      summary: Create Service
      operationId: Create Service
      description: ''
      tags:
        - /Users/maxuden/Studium/BHT/jurilib/.bruno/Services/Create Service.bru
      responses:
        '200':
          description: ''
      parameters:
        - name: organizationID
          in: query
          description: ''
          required: true
          example: '{{organizationID}}'
      requestBody:
        $ref: '#/components/requestBodies/create_service'
  /api/organization/01e13bee-5ec3-49ef-9fa6-e4bfcadb60a3/services/03d92032-c938-45e1-b9c2-d497eeda9a66:
    delete:
      summary: Delete Service
      operationId: Delete Service
      description: ''
      tags:
        - >-
          /Users/maxuden/Studium/BHT/jurilib/.bruno/Services/single
          Service/Delete Service.bru
      responses:
        '200':
          description: ''
    patch:
      summary: Patch Service
      operationId: Patch Service
      description: ''
      tags:
        - >-
          /Users/maxuden/Studium/BHT/jurilib/.bruno/Services/single
          Service/Patch Service.bru
      responses:
        '200':
          description: ''
      requestBody:
        $ref: '#/components/requestBodies/patch_service'
servers:
  - url: http://localhost:3000
components:
  schemas:
    login_employee:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    login_user:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    create_appointment:
      type: object
      properties:
        dateTimeStart:
          type: string
        duration:
          type: number
    create_case:
      type: object
      properties:
        employeeId:
          type: string
        title:
          type: string
        description:
          type: string
    update_case:
      type: object
      properties:
        description:
          type: number
        title:
          type: number
    create_service:
      type: object
      properties:
        description:
          type: string
        type:
          type: string
        price:
          type: number
    patch_service:
      type: object
      properties:
        title:
          type: string
  requestBodies:
    login_employee:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/login_employee'
      description: ''
      required: true
    login_user:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/login_user'
      description: ''
      required: true
    create_appointment:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_appointment'
      description: ''
      required: true
    create_case:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_case'
      description: ''
      required: true
    update_case:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/update_case'
      description: ''
      required: true
    create_service:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_service'
      description: ''
      required: true
    patch_service:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/patch_service'
      description: ''
      required: true
  securitySchemes: {}
